### Где можно поучиться бесплатно или не за дорого:

- [Качаем с торрента (ищем по названиям школ и языков программирования](https://rutracker.org/forum/index.php)
- [code-basics](https://ru.code-basics.com/)
- [Открытое образование](https://openedu.ru/)
- [RS School](https://rs.school/)
- [Coursera](https://www.coursera.org/in-progress)
- [hexlet](https://ru.hexlet.io/my)
- [roadmap frontend](https://roadmap.sh/frontend)
- [Geekbrains бесплатные курсы](https://gb.ru/)
- [beonmax](https://beonmax.com/)
- [stepik](https://stepik.org/learn)
- [habr Бесплатные образовательные курсы: фронтенд-разработка](https://habr.com/ru/company/habr_career/blog/512040/)
- [netology бесплатные курсы](https://netology.ru/)
- [skillbox плейлист](https://live.skillbox.ru/playlists/)
- [ЯндексПрактикумб бесплатная часть ](https://practicum.yandex.ru/catalog/programming/)
